name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0,2,4,6"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git clone git@github.com:HuanYuGod/Scheduled.git
          git config --local user.email "xuhaoyuan2006@outlook.com"
          git config --local user.name "HuanYuGod"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "又是元气满满的一天，啊~~~~~~"
          git push
